'use client'

import Image from 'next/image'

export type ChatMessage = {
  id: string
  role: 'user' | 'assistant'
  content: string
  imageUrl?: string
  uploadedImage?: string
  isStreaming?: boolean
}

interface MessageBubbleProps {
  message: ChatMessage
}

export default function MessageBubble({ message }: MessageBubbleProps) {
  const isUser = message.role === 'user'

  const renderContent = (content: string) => {
    const imageMatch = content.match(/\[GENERATED_IMAGE\]:(https?:\/\/[^\s]+)/)
    if (imageMatch) {
      const preText = content.slice(0, content.indexOf('[GENERATED_IMAGE]:')).trim()
      return (
        <div className="space-y-3">
          {preText && <p className="text-sm leading-relaxed whitespace-pre-wrap">{preText}</p>}
          <div className="rounded-xl overflow-hidden border border-white/10">
            <img
              src={imageMatch[1]}
              alt="Generated image"
              className="w-full max-w-sm rounded-xl object-cover"
            />
          </div>
          <p className="text-xs text-white/40">Image generated by OptiLogix</p>
        </div>
      )
    }

    const parts = content.split(/(\*\*[^*]+\*\*|`[^`]+`|\n)/g)
    return (
      <p className="text-sm leading-relaxed whitespace-pre-wrap">
        {parts.map((part, i) => {
          if (part.startsWith('**') && part.endsWith('**')) {
            return <strong key={i} className="font-semibold text-white">{part.slice(2, -2)}</strong>
          }
          if (part.startsWith('`') && part.endsWith('`')) {
            return <code key={i} className="bg-white/10 px-1 py-0.5 rounded text-violet-300 text-xs font-mono">{part.slice(1, -1)}</code>
          }
          if (part === '\n') return <br key={i} />
          return <span key={i}>{part}</span>
        })}
      </p>
    )
  }

  return (
    <div className={`flex gap-3 animate-slide-up ${isUser ? 'flex-row-reverse' : 'flex-row'}`}>
      <div className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold ${
        isUser
          ? 'bg-violet-500/30 border border-violet-400/40 text-violet-300'
          : 'bg-blue-500/20 border border-blue-400/30 text-blue-300'
      }`}>
        {isUser ? 'You' : 'OL'}
      </div>

      <div className={`max-w-[80%] rounded-2xl px-4 py-3 ${
        isUser ? 'message-user rounded-tr-sm' : 'message-ai rounded-tl-sm'
      }`}>
        {message.uploadedImage && (
          <div className="mb-3">
            <img
              src={message.uploadedImage}
              alt="Uploaded"
              className="max-w-xs rounded-lg border border-white/10 object-cover"
            />
          </div>
        )}
        <div className={`text-white/90 ${message.isStreaming ? 'streaming-cursor' : ''}`}>
          {renderContent(message.content)}
        </div>
      </div>
    </div>
  )
}
